server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.174.129}:3307/yami_shops?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: galaxy@pw@789
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      auto-commit: true
      connection-test-query: SELECT 1
  data:
    redis:
      host: 192.168.174.129
      port: 6379
      database: 0
      password: easymer@redis@2023
logging:
  config: classpath:logback/logback-dev.xml
xxl-job:
  accessToken: default_token
  logPath: /data/applogs/xxl-job/jobhandler
  admin:
    addresses: http://localhost:8080/xxl-job-admin
